Correccion en el compose de Netdata
pablokbs/peladonerd pull request #172
Opened 2021-07-20 15:46 UTC by paganuzzi

agregado version:, services:, se definio volumen netdata-etc y se agrego port para exponer el container al host en el puerto 8080

2021-07-20 16:51 UTC, Goro2030 requested changes
Me parece que lo hiciste demasiado complicado ... Entiendo que @pablokbs  trata de mantener los "composes" simples para que todos los entiendan, y le agregaste demasiadas cosas a este , que son completamente opcionales. Netdata funciona como lo habia armado él, lo unico que no andaba era la persistencia de la db porque faltaba guardar ese directorio, pero igual NetData guarda mucho tiempo "para atrás" de los RDD en memoria ( varias horas )

2021-07-20 16:51 UTC, Goro2030 commented on v2m/19/docker-compose.yaml
>      expose:
Con el PORTS no hace falta el EXPOSE

2021-07-20 17:35 UTC, paganuzzi commented on v2m/19/docker-compose.yaml
>      expose:
en el video Pablo tenia netdata atras de un nginx-proxy entonces para que se configure usaba el expose asi el proxy sabia a que puerto ir. en el original no tenia configurado ports pero lo hice para facilitar la cosa

2021-08-10 13:07 UTC, pablokbs approved these changes

2021-08-10 13:07 UTC, merged